[2024-05-11T16:50:22.226+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-11T16:50:22.268+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Data_Extraction_Transformation_Loading.extract_data manual__2024-05-11T16:23:23.496870+00:00 [queued]>
[2024-05-11T16:50:22.285+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Data_Extraction_Transformation_Loading.extract_data manual__2024-05-11T16:23:23.496870+00:00 [queued]>
[2024-05-11T16:50:22.286+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-11T16:50:22.320+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2024-05-11 16:23:23.496870+00:00
[2024-05-11T16:50:22.331+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Data_Extraction_Transformation_Loading', 'extract_data', 'manual__2024-05-11T16:23:23.496870+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/i202478_dag.py', '--cfg-path', '/tmp/tmpurm3gvoq']
[2024-05-11T16:50:22.333+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask extract_data
[2024-05-11T16:50:22.338+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=87) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-11T16:50:22.339+0000] {standard_task_runner.py:63} INFO - Started process 96 to run task
[2024-05-11T16:50:22.427+0000] {task_command.py:426} INFO - Running <TaskInstance: Data_Extraction_Transformation_Loading.extract_data manual__2024-05-11T16:23:23.496870+00:00 [running]> on host 3c55fa953450
[2024-05-11T16:50:22.624+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Data_Extraction_Transformation_Loading' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T16:23:23.496870+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T16:23:23.496870+00:00'
[2024-05-11T16:50:22.626+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-11T17:11:32.357+0000] {logging_mixin.py:188} INFO - Error occurred while accessing https://twitter.com/dawn_com: HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /dawn_com (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
[2024-05-11T17:14:56.486+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-11T17:14:56.487+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-11T17:14:56.504+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Data_Extraction_Transformation_Loading, task_id=extract_data, run_id=manual__2024-05-11T16:23:23.496870+00:00, execution_date=20240511T162323, start_date=20240511T165022, end_date=20240511T171456
[2024-05-11T17:14:56.576+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-11T17:14:56.625+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-11T17:14:56.638+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
